
site_name: Notas de Aula em Programação em C 
repo_url: https://github.com/lasarojc/fp_notes 
site_description: Notas de aula do curso de Sistemas Programação em C da FACOM/UFU
edit_uri: ""

extra_javascript:
        - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js
        - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
        - javascripts/mathjaxhelper.js

extra_css:
        - css/extra.css

theme:
        name: material
        palette:
           - scheme: default
             toggle:
                icon: material/toggle-switch-off-outline
                name: Switch to dark mode
                accent: deep orange
                primary: blue grey
           - scheme: slate
             toggle:
                icon: material/toggle-switch
                name: Switch to light mode
        language: pt
          #        custom_dir: overrides
        features:
           - search.suggest
           - search.highlight
           - navigation.indexes
           - navigation.tracking

markdown_extensions:
        - toc:
            toc_depth: 5
        - attr_list
          #- mdx_math
        - admonition
        - footnotes
        - pymdownx.arithmatex:
               generic: true
        - pymdownx.betterem:
               smart_enable: all
        - pymdownx.caret
        - pymdownx.critic
        - pymdownx.details
        - pymdownx.emoji:
            emoji_index: !!python/name:materialx.emoji.twemoji
            emoji_generator: !!python/name:materialx.emoji.to_svg
        - pymdownx.highlight:
             linenums: true
             linenums_style: pymdownx-inline
        - pymdownx.inlinehilite
        - pymdownx.magiclink
        - pymdownx.mark
        - pymdownx.smartsymbols
        - pymdownx.superfences:
              custom_fences:
                   - name: mermaid
                     class: mermaid
                     format: !!python/name:pymdownx.superfences.fence_div_format
        - pymdownx.tasklist:
            custom_checkbox: true
        - pymdownx.tabbed
        - pymdownx.tilde
        - pymdownx.keys
        - pymdownx.snippets:
            check_paths: true


copyright: "Copyright © 2021 Lásaro Camargos"

extra:
  social:
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/...
    - icon: fontawesome/brands/github
      link: https://github.com/lasarojc/ds_notes 
      name: These notes on Github
#    - icon: fontawesome/brands/slack
#      link: https://slack.knative.dev
#      name: Slack
  analytics:
    provider: google
    property: G-65TK61CS8M
  version:
    provider: mike


plugins:
        - search
#        - bibtex:
#            bib_file: "refs.bib"
#            cite_style: "pandoc"
#        - drawio-exporter:
#                cache_dir: 'drawio-exporter'
#                drawio_executable: null
#                drawio_args:
#                    - --no-sandbox
#                format: svg
#                sources: '*.drawio'
#





nav:
        - Apresentação: preface.md
        - Capítulos:
            - "O computador é uma máquina burra": cap01.md
            - "Compilação e Execução": cap02.md
            - "Variáveis, Entrada / Saída e Operadores": cap03.md
            - "Variáveis (II)": cap04.md
            - "Seleção Simples": cap05.md
            - "Seleção Simples (II)": cap06.md
            - "Switch": cap07.md
            - "Repetição (I)": cap08.md
            - "Repetição (II)": cap09.md
            - "Arranjos Unidimensionais": cap10.md
            - "Caracteres, Vetores de Caracteres e Strings": cap11.md
            - "Bits, bytes e bases numéricas": cap12.md
            - "Strings e Funções": cap13.md
            - "Funções Úteis I": cap14.md
            - "Arranjos Multidimensionais": cap15.md
            - "Ordenação de Arranjos": cap16.md
            - "Estruturas Não-Homogêneas": cap17.md
            - "Referências": cap18.md
            - "Referências II": cap19.md
            - "Alocação Dinâmica": cap20.md
            - "Vetores de Referências": cap21.md
            - "Alocação Dinâmica II": cap22.md
            - "Arquivos": cap23.md
            - "Navegação dentro do arquivo": cap24.md
            - "Alocação Dinâmica": cap25.md
            - "BigNum": cap26.md
            - "Listas": cap27.md
            - "Filas": cap28.md
            - "Pilhas": cap29.md
            - "Árvores": cap30.md